version: '3.1'

services:
  s3storagefrontend:
    build:
      context: ./ # Local
      dockerfile: Dockerfile_arm64
    #      context: https://github.com/elbosso/s3storagefrontend.git # Build from Github
    container_name: s3storagefronten
    hostname: s3storagefrontend
#    ports:
#      - 7000:7000
    restart: unless-stopped
    env_file:
      - environment.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3storagefrontend.rule=Host(`s3storagefrontend.pi-docker.lab`)"
      - "traefik.http.services.s3storagefrontend.loadbalancer.server.port=7000"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: pi_traefik_proxy
